kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: CP4IADMIN
  namespace: $NAMESPACE1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER1'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER2'  
   - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER3'  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: CP4IADMIN
  namespace: $NAMESPACE2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER1'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER2'  
   - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'IAM#$USER3'  
